language: node_js
node_js: 
  - "8"
script:
  - cd functions
  - npm install
  - echo "installing dependencys..."
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  